### ISSUE TITLE
arm平台运行出现错误

### ISSUE THREAD

**Issue by 12441409** [myshell-ai/MeloTTS#102]
root@794d5155472c:/# melo
Traceback (most recent call last):
  File "/usr/local/bin/melo", line 33, in <module>
    sys.exit(load_entry_point('melotts', 'console_scripts', 'melo')())
  File "/usr/local/bin/melo", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'melo.main'

**Comment by otonoton** [comment]
Same issue here
