### ISSUE TITLE
Docker build error.

### ISSUE THREAD

**Issue by arthurwolf** [myshell-ai/MeloTTS#128]
Trying to install folllowing the instructions at https://github.com/myshell-ai/MeloTTS/blob/main/docs/install.md

What happens (after a git copy) :

```bash

╭─arthur at aquarelle in ~/dev/ai/MeloTTS on main✔ 24-05-07 - 23:35:27
╰─(base) ⠠⠵ docker build -t melotts .                                                                                                                                                    on main|✔
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  29.04MB
Step 1/8 : FROM python:3.9-slim
 ---> a8260aeae86e
Step 2/8 : WORKDIR /app
 ---> Using cache
 ---> 224330a24d00
Step 3/8 : COPY . /app
 ---> Using cache
 ---> 5e1d5add8180
Step 4/8 : RUN apt-get update && apt-get install -y     build-essential libsndfile1     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> e70782d33c30
Step 5/8 : RUN pip install -e .
 ---> Using cache
 ---> 24dbac85d7d0
Step 6/8 : RUN python -m unidic download
 ---> Using cache
 ---> 58ac3b7f2ca4
Step 7/8 : RUN python melo/init_downloads.py
 ---> Running in 3a0bfdab6fe0
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package cmudict to /root/nltk_data...
[nltk_data]   Unzipping corpora/cmudict.zip.
Traceback (most recent call last):
  File "/app/melo/init_downloads.py", line 5, in <module>
    from melo.api import TTS
  File "/app/melo/api.py", line 18, in <module>
    from .download_utils import load_or_download_config, load_or_download_model
  File "/app/melo/download_utils.py", line 4, in <module>
    from cached_path import cached_path
  File "/usr/local/lib/python3.9/site-packages/cached_path/__init__.py", line 13, in <module>
    from ._cached_path import cached_path
  File "/usr/local/lib/python3.9/site-packages/cached_path/_cached_path.py", line 15, in <module>
    from .schemes import (
  File "/usr/local/lib/python3.9/site-packages/cached_path/schemes/__init__.py", line 6, in <module>
    from .s3 import S3Client
  File "/usr/local/lib/python3.9/site-packages/cached_path/schemes/s3.py", line 16, in <module>
    class S3Client(SchemeClient):
  File "/usr/local/lib/python3.9/site-packages/cached_path/schemes/s3.py", line 18, in S3Client
    botocore.exceptions.HTTPClientError,
AttributeError: module 'botocore.exceptions' has no attribute 'HTTPClientError'
The command '/bin/sh -c python melo/init_downloads.py' returned a non-zero code: 1
╭─arthur at aquarelle in ~/dev/ai/MeloTTS on main✔ 24-05-07 - 23:37:23
╰─(base) ⠠⠵                            

```

Thank you.

**Comment by LaptopDev** [comment]
@samtin0x thanks, curious why that worked

**Comment by replete** [comment]
Yep my build is also going nuts repeating version numbers lowering by one:
```
> => # Collecting boto3<2.0,>=1.0
 => => #   Downloading boto3-1.34.60-py3-none-any.whl (139 kB)
 => => #      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.3/139.3 kB 5.3 MB/s eta 0:00:00
 => => # Collecting botocore<1.35.0,>=1.34.60
 => => #   Downloading botocore-1.34.60-py3-none-any.whl (12.0 MB)
```

**Comment by Eyalm321** [comment]
please update this , build takes a long time to download all botocore versions

**Comment by xipingL** [comment]
fuck botocore
