### ISSUE TITLE
ModuleNotFoundError: No module named 'melo.text'

### ISSUE THREAD

**Issue by Mixomo** [myshell-ai/MeloTTS#141]
Hello, I'm trying to train a custom model with a Spanish dataset; however, when I ran the training command (!python preprocess_text.py --metadata /content/metadata.list), I received the next error:

Traceback (most recent call last):
  File "/content/MeloTTS/melo/preprocess_text.py", line 8, in <module>
    from text.cleaner import clean_text_bert
  File "/content/MeloTTS/melo/text/cleaner.py", line 1, in <module>
    from . import chinese, japanese, english, chinese_mix, korean, french, spanish
  File "/content/MeloTTS/melo/text/korean.py", line 12, in <module>
    from melo.text.ko_dictionary import english_dictionary, etc_dictionary
ModuleNotFoundError: No module named 'melo.text'

can you help me, pelase? :( Thanks!

PS:  any Melo Spanish checkpoint must be downloaded? Why is the correct path?

**Comment by RedBluePrinter** [comment]
Try changing the 'melo.text' in the Source code file to 'text'.  Or install the folder to your python libraries(build). for me "melo.*" did not work until it was linked to my python.

**Comment by itsbilyatt** [comment]
I am also getting same error

**Comment by cherloner** [comment]
我按照报错中的提示将korean.py文件移出了text文件，然后再到cleaner.py文件中将与korean有关的代码注释掉，之后就可以正常运行了。
