### ISSUE TITLE
Dockerfile deployment Issues

### ISSUE THREAD

**Issue by cmurrayis** [myshell-ai/MeloTTS#167]
Trying to use the Dockerfile and get the following error:

```
 ---> Running in 8bb1dcf92b93
/usr/local/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package cmudict to /root/nltk_data...
[nltk_data]   Unzipping corpora/cmudict.zip.
Traceback (most recent call last):
  File "/app/melo/init_downloads.py", line 5, in <module>
    from melo.api import TTS
  File "/app/melo/api.py", line 18, in <module>
    from .download_utils import load_or_download_config, load_or_download_model
  File "/app/melo/download_utils.py", line 4, in <module>
    from cached_path import cached_path
  File "/usr/local/lib/python3.9/site-packages/cached_path/__init__.py", line 13, in <module>
    from ._cached_path import cached_path
  File "/usr/local/lib/python3.9/site-packages/cached_path/_cached_path.py", line 15, in <module>
    from .schemes import (
  File "/usr/local/lib/python3.9/site-packages/cached_path/schemes/__init__.py", line 6, in <module>
    from .r2 import R2Client
  File "/usr/local/lib/python3.9/site-packages/cached_path/schemes/r2.py", line 18, in <module>
    class R2Client(SchemeClient):
  File "/usr/local/lib/python3.9/site-packages/cached_path/schemes/r2.py", line 20, in R2Client
    botocore.exceptions.HTTPClientError,
AttributeError: module 'botocore.exceptions' has no attribute 'HTTPClientError'
```

**Comment by yyaaron** [comment]
pls refer to https://github.com/myshell-ai/MeloTTS/pull/124

**Comment by Meiye-lj** [comment]
Creating a Dockerfile for MeloTTS, see https://github.com/Meiye-lj/Dockerfiles/blob/76c88309a4bb7b7070441bed3b4b72231f5349b8/MeloTTS/Dockerfile
