### ISSUE TITLE
403 client error for myshell-public-repo-hosting.s3.amazonaws.com

### ISSUE THREAD

**Issue by jadechip** [myshell-ai/MeloTTS#169]
Hi did the permissions on the S3 bucker hosting the retrained models change? I can't seem to access them anymore?
```
Traceback (most recent call last):
  File "/workspace/MeloTTS/melo/train.py", line 636, in <module>
    run()
  File "/workspace/MeloTTS/melo/train.py", line 169, in run
    pretrain_G, pretrain_D, pretrain_dur = load_pretrain_model()
  File "/workspace/MeloTTS/melo/download_utils.py", line 67, in load_pretrain_model
    return [cached_path(url) for url in PRETRAINED_MODELS.values()]
  File "/workspace/MeloTTS/melo/download_utils.py", line 67, in <listcomp>
    return [cached_path(url) for url in PRETRAINED_MODELS.values()]
  File "/usr/local/lib/python3.10/dist-packages/cached_path/_cached_path.py", line 204, in cached_path
    file_path, etag = get_from_cache(url_or_filename, cache_dir, quiet=quiet, progress=progress)
  File "/usr/local/lib/python3.10/dist-packages/cached_path/_cached_path.py", line 317, in get_from_cache
    etag = client.get_etag()
  File "/usr/local/lib/python3.10/dist-packages/cached_path/schemes/http.py", line 58, in get_etag
    return self.head_response.headers.get("ETag")
  File "/usr/local/lib/python3.10/dist-packages/cached_path/schemes/http.py", line 51, in head_response
    self.validate_response(response)
  File "/usr/local/lib/python3.10/dist-packages/cached_path/schemes/http.py", line 98, in validate_response
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myshell-public-repo-hosting.s3.amazonaws.com/openvoice/basespeakers/pretrained/G.pth
```

**Comment by jeremy110** [comment]
The url is modify to https://myshell-public-repo-host.s3.amazonaws.com/openvoice/basespeakers/pretrained/G.pth

**Comment by jadechip** [comment]
Thank you!
