### ISSUE TITLE
Unable to train with strange error...

### ISSUE THREAD

**Issue by mah92** [myshell-ai/MeloTTS#175]
Hi
I'm unable to train. 
commit id: 5b538481e24e0d578955be32a95d88fcbde26dc8
Using [melotts_metadata_english.csv](https://github.com/user-attachments/files/16566127/melotts_metadata_english.csv)
When I type: 
```
$python3 preprocess_text.py --metadata data/Quran/melotts_metadata_english.csv
```
I get:
```
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.2) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
  File "/home/android/.local/lib/python3.10/site-packages/MeCab/__init__.py", line 137, in __init__
    super(Tagger, self).__init__(args)
RuntimeError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/android/TTS/MeloTTS/MeloTTS/melo/preprocess_text.py", line 8, in <module>
    from text.cleaner import clean_text_bert
  File "/home/android/TTS/MeloTTS/MeloTTS/melo/text/cleaner.py", line 1, in <module>
    from . import chinese, japanese, english, chinese_mix, korean, french, spanish
  File "/home/android/TTS/MeloTTS/MeloTTS/melo/text/japanese.py", line 367, in <module>
    _TAGGER = MeCab.Tagger()
  File "/home/android/.local/lib/python3.10/site-packages/MeCab/__init__.py", line 139, in __init__
    raise RuntimeError(error_info(rawargs)) from ee
RuntimeError: 
----------------------------------------------------------

Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/SamuraiT/mecab-python3#common-issues

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/SamuraiT/mecab-python3/issues

issueを英語で書く必要はありません。

------------------- ERROR DETAILS ------------------------
arguments: 
default dictionary path: /home/android/.local/lib/python3.10/site-packages/unidic/dicdir
[ifs] no such file or directory: /home/android/.local/lib/python3.10/site-packages/unidic/dicdir/mecabrc
----------------------------------------------------------
```

**Comment by Andychung1229** [comment]
#135
