### ISSUE TITLE
Solutions for Docker compilation errors.

### ISSUE THREAD

**Issue by foxlesbiao** [myshell-ai/MeloTTS#196]
error 1. 
```
=> ERROR [9/9] RUN python melo/init_downloads.py                                                                 29.4s
------
 > [9/9] RUN python melo/init_downloads.py:
5.995 /usr/local/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: resume_download is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use force_download=True.
5.995   warnings.warn(
8.566 [nltk_data] Downloading package averaged_perceptron_tagger to
8.566 [nltk_data]     /root/nltk_data...
9.168 [nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
9.206 [nltk_data] Downloading package cmudict to /root/nltk_data...
9.732 [nltk_data]   Unzipping corpora/cmudict.zip.
27.13 Traceback (most recent call last):
27.13   File "/app/melo/init_downloads.py", line 5, in <module>
27.13     from melo.api import TTS
27.13   File "/app/melo/api.py", line 18, in <module>
27.13     from .download_utils import load_or_download_config, load_or_download_model
27.13   File "/app/melo/download_utils.py", line 4, in <module>
27.13     from cached_path import cached_path
27.13   File "/usr/local/lib/python3.9/site-packages/cached_path/__init__.py", line 13, in <module>
27.13     from ._cached_path import cached_path
27.13   File "/usr/local/lib/python3.9/site-packages/cached_path/_cached_path.py", line 15, in <module>
27.13     from .schemes import (
27.13   File "/usr/local/lib/python3.9/site-packages/cached_path/schemes/__init__.py", line 6, in <module>
27.13     from .r2 import R2Client
27.13   File "/usr/local/lib/python3.9/site-packages/cached_path/schemes/r2.py", line 18, in <module>
27.13     class R2Client(SchemeClient):
27.13   File "/usr/local/lib/python3.9/site-packages/cached_path/schemes/r2.py", line 20, in R2Client
27.13     botocore.exceptions.HTTPClientError,
27.13 AttributeError: module 'botocore.exceptions' has no attribute 'HTTPClientError'
------
Dockerfile:13
--------------------
  11 |     RUN pip install -e .
  12 |     RUN python -m unidic download
  13 | >>> RUN python melo/init_downloads.py
  14 |
  15 |     CMD ["python", "./melo/app.py", "--host", "0.0.0.0", "--port", "8888"]
--------------------
ERROR: failed to solve: process "/bin/sh -c python melo/init_downloads.py" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/uamitxq2tdjgk4yto5awpl8xf
```
error 2. 
```
 => ERROR [9/9] RUN python melo/init_downloads.py                                                                 29.4s
------
 > [9/9] RUN python melo/init_downloads.py:
5.995 /usr/local/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: resume_download is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use force_download=True.
5.995   warnings.warn(
8.566 [nltk_data] Downloading package averaged_perceptron_tagger to
8.566 [nltk_data]     /root/nltk_data...
9.168 [nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
9.206 [nltk_data] Downloading package cmudict to /root/nltk_data...
9.732 [nltk_data]   Unzipping corpora/cmudict.zip.
27.13 Traceback (most recent call last):
27.13   File "/app/melo/init_downloads.py", line 5, in <module>
27.13     from melo.api import TTS
27.13   File "/app/melo/api.py", line 18, in <module>
27.13     from .download_utils import load_or_download_config, load_or_download_model
27.13   File "/app/melo/download_utils.py", line 4, in <module>
27.13     from cached_path import cached_path
27.13   File "/usr/local/lib/python3.9/site-packages/cached_path/__init__.py", line 13, in <module>
27.13     from ._cached_path import cached_path
27.13   File "/usr/local/lib/python3.9/site-packages/cached_path/_cached_path.py", line 15, in <module>
27.13     from .schemes import (
27.13   File "/usr/local/lib/python3.9/site-packages/cached_path/schemes/__init__.py", line 6, in <module>
27.13     from .r2 import R2Client
27.13   File "/usr/local/lib/python3.9/site-packages/cached_path/schemes/r2.py", line 18, in <module>
27.13     class R2Client(SchemeClient):
27.13   File "/usr/local/lib/python3.9/site-packages/cached_path/schemes/r2.py", line 20, in R2Client
27.13     botocore.exceptions.HTTPClientError,
27.13 AttributeError: module 'botocore.exceptions' has no attribute 'HTTPClientError'
------
Dockerfile:13
--------------------
  11 |     RUN pip install -e .
  12 |     RUN python -m unidic download
  13 | >>> RUN python melo/init_downloads.py
  14 |
  15 |     CMD ["python", "./melo/app.py", "--host", "0.0.0.0", "--port", "8888"]
--------------------
ERROR: failed to solve: process "/bin/sh -c python melo/init_downloads.py" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/uamitxq2tdjgk4yto5awpl8xf
```
Solution.
Add `botocore==1.27.0` to requirements.txt.
Add `RUN pip install --upgrade pip` to dockerfile.
![图片](https://github.com/user-attachments/assets/46fd123c-0871-4ef1-90a6-8c02e9707181)
![图片](https://github.com/user-attachments/assets/91488f37-5294-4a00-b40b-94b717a263ec)

**Comment by foxlesbiao** [comment]
![图片](https://github.com/user-attachments/assets/24bd9028-7534-4181-84dd-6976a0b0749e)
How to use the CPU during custom training?
