### ISSUE TITLE
python 3.10 required for install

### ISSUE THREAD

**Issue by jowparks** [myshell-ai/MeloTTS#208]
Was stuck in a loop of trying to resolve boto/botocore dependencies. Figured out it was because my virtualenv was 3.9, the install only works with 3.10. The repo should be updated.

https://academy.finxter.com/hugging-face-course-5-6-text-to-speech-with-melotts/

```
If you’re lucky the build may finish and the terminal will finish all [7/7] steps (skip ahead to Running the MeloTTS model). If you’re less lucky like me your process will get stuck trying to install the following dependency over and over in step [5/7]:

 => => # Downloading botocore-1.21.5-py3-none-any.whl (7.7 MB)
 => => #   ━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 21.8 MB/s eta 0:00:00
 => => # Collecting boto3<2.0,>=1.0
 => => # Downloading boto3-1.18.4-py3-none-any.whl (131 kB)
 => => #   ━━━━━━━━━━━━━━━━━━━━━ 131.6/131.6 kB 17.8 MB/s eta 0:00:00
```

**Comment by smlkdev** [comment]
I had the same issue yesteday, finally installed some ready to use docker image from 3rd party. I tried to modify the setup script (eg. `--no-deps`) but I failed.

**Comment by jowparks** [comment]
Both docker and local worked for me if I used python 3.10

**Comment by Ky-Ng** [comment]
Thank you this helped! I had to add the following line to `melo/app.py` in order to get the docker container to work as well.

```
import nltk
nltk.download('averaged_perceptron_tagger_eng')
```

**Comment by ramonrovirosa** [comment]
For anyone getting the following `HTTPClientError` issue with python 3.9

```
11.74 Traceback (most recent call last):
11.74   File "/app/melo/init_downloads.py", line 5, in <module>
11.74     from melo.api import TTS
11.74   File "/app/melo/api.py", line 18, in <module>
11.74     from .download_utils import load_or_download_config, load_or_download_model
11.74   File "/app/melo/download_utils.py", line 4, in <module>
11.74     from cached_path import cached_path
11.74   File "/usr/local/lib/python3.9/site-packages/cached_path/__init__.py", line 13, in <module>
11.74     from ._cached_path import cached_path
11.74   File "/usr/local/lib/python3.9/site-packages/cached_path/_cached_path.py", line 15, in <module>
11.74     from .schemes import (
11.74   File "/usr/local/lib/python3.9/site-packages/cached_path/schemes/__init__.py", line 6, in <module>
11.74     from .r2 import R2Client
11.74   File "/usr/local/lib/python3.9/site-packages/cached_path/schemes/r2.py", line 19, in <module>
11.74     class R2Client(SchemeClient):
11.74   File "/usr/local/lib/python3.9/site-packages/cached_path/schemes/r2.py", line 21, in R2Client
11.74     botocore.exceptions.HTTPClientError,
11.74 AttributeError: module 'botocore.exceptions' has no attribute 'HTTPClientError'
```

Upgrading to python 3.10 as suggested above should fix it. Posting this for better/easier searchability

**Comment by zerosoul13** [comment]
I recently cloned this repo and found boto libraries downloading endlessly. To resolve the issue, all did was to updated the Dockerfile to `FROM python:3.10-slim`  instead of  `FROM python:3.9-slim`

**Comment by NINE-J** [comment]
Somewhere in requirements.txt or MeloTTS dependency, the boto3 version range is twisted.
If it's below pip 21.x, this seems to happen due to weak dependency collision detection.

I solved it by adding the command to update the pip first in Dockerfile.

```dockerfile
...
RUN pip install --upgrade pip setuptools wheel
...
```
