### ISSUE TITLE
encoding error in train.py under windows cmd line

### ISSUE THREAD

**Issue by shirubei** [myshell-ai/MeloTTS#220]
Just FYI.

Got an encoding error when run train.py under windows cmd line:

Traceback (most recent call last):
  File "D:\Python311.6\melotts\MeloTTS-main\melo\train.py", line 635, in <module>
    run()
  File "D:\Python311.6\melotts\MeloTTS-main\melo\train.py", line 50, in run
    hps = utils.get_hparams()
          ^^^^^^^^^^^^^^^^^^^
  File "D:\Python311.6\melotts\MeloTTS-main\melo\utils.py", line 273, in get_hparams
    data = f.read()
           ^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 3640: illegal multibyte sequence

To solve this issue, modify the souce code of function get_hparams in melo\utils.py
added encoding option when calling open()

    config_save_path = os.path.join(model_dir, "config.json")
    if init:
        with open(config_path, "r", encoding='utf-8') as f:
            data = f.read()
        with open(config_save_path, "w", encoding='utf-8') as f:
            f.write(data)
    else:
        with open(config_save_path, "r", encoding='utf-8') as f:
            data = f.read()

**Comment by shirubei** [comment]
FYI only
