### ISSUE TITLE
pip Install Can't Find Requirements.txt

### ISSUE THREAD

**Issue by timhagel** [myshell-ai/MeloTTS#41]
### Explanation
When installing MeloTTS via the PyPI package receiving error indicating that it can't find the requirements.txt file 
### Environment 
- Intel Mac Sonoma 14.0
- Python 3.9.13
- pip 24.0
### Comand and Output
```
$ pip3.9 install melotts
Collecting melotts
  Using cached melotts-0.1.1.tar.gz (4.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/hc/npzs9snx1m91qqb69ztyym8c0000gq/T/pip-build-env-ismo191n/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/hc/npzs9snx1m91qqb69ztyym8c0000gq/T/pip-build-env-ismo191n/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/hc/npzs9snx1m91qqb69ztyym8c0000gq/T/pip-build-env-ismo191n/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/hc/npzs9snx1m91qqb69ztyym8c0000gq/T/pip-build-env-ismo191n/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/hc/npzs9snx1m91qqb69ztyym8c0000gq/T/pip-install-8d_wg6c2/melotts_3fd10f3406e145fbbe4488f43feb9e02/requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by AbnormalPilot** [comment]
try running: `pip install -r requirements.txt`

**Comment by timhagel** [comment]
This was a problem with the PyPI package (Not locally building), but this method of install is currently removed from the install page

**Comment by mostafa-razavi** [comment]
I see the same error when I try to run `pip install melotts` (which is supposed to install version 0.1.1)
