### ISSUE TITLE
installation via Docker failure 

### ISSUE THREAD

**Issue by bullkq** [myshell-ai/MeloTTS#48]
RUN apt-get update && apt-get install -y \
6

    build-essential libsndfile1 \
7

    && rm -rf /var/lib/apt/lists/*
8

9

RUN pip install -e .
10

RUN python -m unidic download
Downloading UniDic v3.1.0+2021-08-31...
download url: https://cotonoha-dic.s3-ap-northeast-1.amazonaws.com/unidic-3.1.0.zip
Dictionary version: 3.1.0+2021-08-31
unidic-3.1.0.zip: 0.00B [00:00, ?B/s]unidic-3.1.0.zip: 0.00B [00:00, ?B/s]
Traceback (most recent call last):
File "/usr/local/lib/python3.9/urllib/request.py", line 1346, in do_open
h.request(req.get_method(), req.selector, req.data, headers,
File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.9/http/client.py", line 1331, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
self.send(msg)
File "/usr/local/lib/python3.9/http/client.py", line 980, in send
self.connect()
File "/usr/local/lib/python3.9/http/client.py", line 1454, in connect
self.sock = self._context.wrap_socket(self.sock,
File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
return self.sslsocket_class._create(
File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
self.do_handshake()
File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.9/site-packages/unidic/__main__.py", line 17, in <module>
plac.call(commands[command], sys.argv[1:])
File "/usr/local/lib/python3.9/site-packages/plac_core.py", line 436, in call
cmd, result = parser.consume(arglist)
File "/usr/local/lib/python3.9/site-packages/plac_core.py", line 287, in consume
return cmd, self.func(*(args + varargs + extraopts), **kwargs)
File "/usr/local/lib/python3.9/site-packages/unidic/download.py", line 104, in download_version
download_and_clean(dictinfo['version'], dictinfo['url'])
File "/usr/local/lib/python3.9/site-packages/unidic/download.py", line 62, in download_and_clean
download_progress(url, fname)
File "/usr/local/lib/python3.9/site-packages/unidic/download.py", line 38, in download_progress
urlretrieve(url, filename=fname, reporthook=t.update_to, data=None)
File "/usr/local/lib/python3.9/urllib/request.py", line 239, in urlretrieve
with contextlib.closing(urlopen(url, data)) as fp:
File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
return opener.open(url, data, timeout)
File "/usr/local/lib/python3.9/urllib/request.py", line 517, in open
response = self._open(req, data)
File "/usr/local/lib/python3.9/urllib/request.py", line 534, in _open
result = self._call_chain(self.handle_open, protocol, protocol +
File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
result = func(*args)
File "/usr/local/lib/python3.9/urllib/request.py", line 1389, in https_open
return self.do_open(http.client.HTTPSConnection, req,
File "/usr/local/lib/python3.9/urllib/request.py", line 1349, in do_open
raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1129)>

11

RUN python melo/init_downloads.py
12

13

CMD ["python", "./melo/app.py", "--host", "0.0.0.0", "--port", "8888"]

wsl2:unbuntu 22.04
how can i correct this errors? thank you.

**Comment by Zengyi-Qin** [comment]
Your network has problems. The program can't download the model files
