### ISSUE TITLE
 unidic 国内无法下载？

### ISSUE THREAD

**Issue by bergli2020** [myshell-ai/MeloTTS#62]
download url: https://cotonoha-dic.s3-ap-northeast-1.amazonaws.com/unidic-3.1.0.zip 国内无法访问，请教下如何解决？

RUN python3 -m unidic download:                                      
2.445 Downloading UniDic v3.1.0+2021-08-31...
2.506 download url: https://cotonoha-dic.s3-ap-northeast-1.amazonaws.com/unidic-3.1.0.zip
2.506 Dictionary version: 3.1.0+2021-08-31
unidic-3.1.0.zip: 0.00B [00:00, ?B/s]
2.866 Traceback (most recent call last):
2.866   File "/usr/local/lib/python3.9/urllib/request.py", line 1346, in do_open
2.900     h.request(req.get_method(), req.selector, req.data, headers,
2.900   File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
2.934     self._send_request(method, url, body, headers, encode_chunked)
2.934   File "/usr/local/lib/python3.9/http/client.py", line 1331, in _send_request
2.934     self.endheaders(body, encode_chunked=encode_chunked)
2.934   File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
2.934     self._send_output(message_body, encode_chunked=encode_chunked)
2.934   File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
2.935     self.send(msg)
2.935   File "/usr/local/lib/python3.9/http/client.py", line 980, in send
2.935     self.connect()
2.935   File "/usr/local/lib/python3.9/http/client.py", line 1454, in connect
2.936     self.sock = self._context.wrap_socket(self.sock,
2.936   File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
2.936     return self.sslsocket_class._create(
2.936   File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
2.937     self.do_handshake()
2.937   File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
2.937     self._sslobj.do_handshake()
2.937 ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by liurongsheng** [comment]
确实需要梯子才行

**Comment by gotoolkits** [comment]
这个库是必须的还是可以忽略此下载？

**Comment by YingjiaoLiu** [comment]
用梯子下载好zip然后如何安装呢？远程服务器没法用命令`python3 -m unidic download`安装

**Comment by Game5048-bilibili** [comment]
同问qwq`(python_venv) E:\PersonalProject\LiveBulletComments\MeloTTS-0.1.2>python
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import melo.api
Traceback (most recent call last):
  File "E:\PersonalProject\LiveBulletComments\python_venv\lib\site-packages\MeCab\__init__.py", line 133, in __init__
    super(Tagger, self).__init__(args)
RuntimeError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\PersonalProject\LiveBulletComments\MeloTTS-0.1.2\melo\api.py", line 13, in <module>
    from . import utils
  File "E:\PersonalProject\LiveBulletComments\MeloTTS-0.1.2\melo\utils.py", line 13, in <module>
    from .text.cleaner import clean_text
  File "E:\PersonalProject\LiveBulletComments\MeloTTS-0.1.2\melo\text\cleaner.py", line 1, in <module>
    from . import chinese, japanese, english, chinese_mix, korean, french, spanish
  File "E:\PersonalProject\LiveBulletComments\MeloTTS-0.1.2\melo\text\japanese.py", line 367, in <module>
    _TAGGER = MeCab.Tagger()
  File "E:\PersonalProject\LiveBulletComments\python_venv\lib\site-packages\MeCab\__init__.py", line 135, in __init__
    raise RuntimeError(error_info(rawargs)) from ee
RuntimeError:
----------------------------------------------------------

Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/SamuraiT/mecab-python3#common-issues

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/SamuraiT/mecab-python3/issues

issueを英語で書く必要はありません。

------------------- ERROR DETAILS ------------------------
arguments:
[ifs] no such file or directory: E:\PersonalProject\LiveBulletComments\python_venv\lib\site-packages\unidic\dicdir\mecabrc
----------------------------------------------------------`

**Comment by Game5048-bilibili** [comment]
我也想问qwq,大家都是怎么安装的

**Comment by Game5048-bilibili** [comment]
我解决了

**Comment by zhangguangxun** [comment]
> 我解决了

请教一下怎么解决的呢？

**Comment by Game5048-bilibili** [comment]
首先你需要pip install unidec
然后找你的python的路径，我这里是venv所以就拿venv说
我的路径是`./python_venv/Lib/site-packages`
接着你需要找`unidec`和`unidec_lite`两个文件夹
我当时发现是unidec_lite中有个dicdir文件夹，而unidec中没有，而且报错中显示的目标也在这个文件夹中，所以我把dicdir复制了一份到unidec文件夹中，然后就可以了。

但是因为网络问题，这个程序还要下载亚马逊和huggingface里的配置文件和模型，我尝试过手动导入，但是我代码基础差看不懂，所以还是运行不了，你们如果解决了麻烦告诉我！！提前说声感谢

**Comment by Game5048-bilibili** [comment]
> 首先你需要pip install unidec 然后找你的python的路径，我这里是venv所以就拿venv说 我的路径是`./python_venv/Lib/site-packages` 接着你需要找`unidec`和`unidec_lite`两个文件夹 我当时发现是unidec_lite中有个dicdir文件夹，而unidec中没有，而且报错中显示的目标也在这个文件夹中，所以我把dicdir复制了一份到unidec文件夹中，然后就可以了。
> 
> 但是因为网络问题，这个程序还要下载亚马逊和huggingface里的配置文件和模型，我尝试过手动导入，但是我代码基础差看不懂，所以还是运行不了，你们如果解决了麻烦告诉我！！提前说声感谢

要是需要我提供文件夹请@我

**Comment by zhangguangxun** [comment]
> 首先你需要pip install unidec 然后找你的python的路径，我这里是venv所以就拿venv说 我的路径是`./python_venv/Lib/site-packages` 接着你需要找`unidec`和`unidec_lite`两个文件夹 我当时发现是unidec_lite中有个dicdir文件夹，而unidec中没有，而且报错中显示的目标也在这个文件夹中，所以我把dicdir复制了一份到unidec文件夹中，然后就可以了。
> 
> 但是因为网络问题，这个程序还要下载亚马逊和huggingface里的配置文件和模型，我尝试过手动导入，但是我代码基础差看不懂，所以还是运行不了，你们如果解决了麻烦告诉我！！提前说声感谢

感谢！我去试一下，感谢分享，有进展继续交流！

**Comment by Game5048-bilibili** [comment]
呃，我已经全部解决了！

**Comment by MissingTwins** [comment]
Try this in windows cmd
```
set HTTP_PROXY=http://127.0.0.1:7890
set HTTPS_PROXY=http://127.0.0.1:7890
python -m unidic download
```
Try this in bash
```
export HTTP_PROXY=http://127.0.0.1:7890
export HTTPS_PROXY=http://127.0.0.1:7890
python -m unidic download
```

**Comment by Game5048-bilibili** [comment]
> Try this in windows cmd
> 
> ```
> set HTTP_PROXY=http://127.0.0.1:7890
> set HTTPS_PROXY=http://127.0.0.1:7890
> python -m unidic download
> ```
> 
> Try this in bash
> 
> ```
> export HTTP_PROXY=http://127.0.0.1:7890
> export HTTPS_PROXY=http://127.0.0.1:7890
> python -m unidic download
> ```

Yeah! It works!
Before inputing these, you need a proxy to connect AWS.

**Comment by yiJianX** [comment]
> 呃，我已经全部解决了！

你好，请问方便讲述一下是如何全部解决的吗？

**Comment by hey135** [comment]
> 呃，我已经全部解决了！
怎么解决的这个问题呀？

**Comment by hey135** [comment]
> 呃，我已经全部解决了！

怎么解决的呀

**Comment by morganwang010** [comment]
1, manaul download the unidic.zip from https://cotonoha-dic.s3-ap-northeast-1.amazonaws.com/unidic-3.1.0.zip,
2, cp unidic-3.1.0.zip to /usr/local/lib/python3.9/site-packages/unidic/ and rename it to unidic.zip
3, change /usr/local/lib/python3.9/site-packages/unidic/download.py   line 93 , function download_version, comment all except download_and_clean(),
4, change the download_and_clean two parameter anything you want
5, change /usr/local/lib/python3.9/site-packages/unidic/download.py  line 63, comment the download_process
then execut python -m unidic download again ,  it will be OK

**Comment by Super-Tree** [comment]
> 1, manaul download the unidic.zip from https://cotonoha-dic.s3-ap-northeast-1.amazonaws.com/unidic-3.1.0.zip, 2, cp unidic-3.1.0.zip to /usr/local/lib/python3.9/site-packages/unidic/ and rename it to unidic.zip 3, change /usr/local/lib/python3.9/site-packages/unidic/download.py line 93 , function download_version, comment all except download_and_clean(), 4, change the download_and_clean two parameter anything you want 5, change /usr/local/lib/python3.9/site-packages/unidic/download.py line 63, comment the download_process then execut python -m unidic download again , it will be OK

Yes,it works!

**Comment by zhangguangxun** [comment]
> 1, manaul download the unidic.zip from https://cotonoha-dic.s3-ap-northeast-1.amazonaws.com/unidic-3.1.0.zip, 2, cp unidic-3.1.0.zip to /usr/local/lib/python3.9/site-packages/unidic/ and rename it to unidic.zip 3, change /usr/local/lib/python3.9/site-packages/unidic/download.py line 93 , function download_version, comment all except download_and_clean(), 4, change the download_and_clean two parameter anything you want 5, change /usr/local/lib/python3.9/site-packages/unidic/download.py line 63, comment the download_process then execut python -m unidic download again , it will be OK

It works and help a lot

**Comment by zhangguangxun** [comment]
> > 呃，我已经全部解决了！
> 
> 怎么解决的呀

unidic的下载你可以参考[morganwang010](https://github.com/morganwang010)的方法，我试过是可行的
hugging face上的模型下载你可以考虑切换镜像源下载
参考配置代码`pip install -U huggingface_hub` `export HF_ENDPOINT=https://hf-mirror.com`
nltk的下载问题可以参考知乎文章：https://zhuanlan.zhihu.com/p/347931749
我通过上述方法调通了

**Comment by yiJianX** [comment]
好的好的，我已经解决了，谢谢你啦

zhangguangxun ***@***.***> 于2024年4月20日周六 17:35写道：

**Comment by iskefu** [comment]
> > 首先你需要pip install unidec 然后找你的python的路径，我这里是venv所以就拿venv说 我的路径是`./python_venv/Lib/site-packages` 接着你需要找`unidec`和`unidec_lite`两个文件夹 我当时发现是unidec_lite中有个dicdir文件夹，而unidec中没有，而且报错中显示的目标也在这个文件夹中，所以我把dicdir复制了一份到unidec文件夹中，然后就可以了。
> > 但是因为网络问题，这个程序还要下载亚马逊和huggingface里的配置文件和模型，我尝试过手动导入，但是我代码基础差看不懂，所以还是运行不了，你们如果解决了麻烦告诉我！！提前说声感谢
> 
> 感谢！我去试一下，感谢分享，有进展继续交流！

这个可以解决python -m unidic download网络错误问题，
我开魔法也解决不了，这样确实解决了
剩下的就是开魔法一路通行，还要下个几百m

**Comment by wanglongpeng1** [comment]
OpenVoice version: v2版本 demo_part3 第三个cell 会出现这个问题 
An error occured while synchronizing the model guillaumekln/faster-whisper-medium from the Hugging Face Hub:
An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.
Trying to load the model directly from the local cache, if it exists.

**Comment by zhengrui18** [comment]
> 首先你需要pip install unidec 然后找你的python的路径，我这里是venv所以就拿venv说 我的路径是`./python_venv/Lib/site-packages` 接着你需要找`unidec`和`unidec_lite`两个文件夹 我当时发现是unidec_lite中有个dicdir文件夹，而unidec中没有，而且报错中显示的目标也在这个文件夹中，所以我把dicdir复制了一份到unidec文件夹中，然后就可以了。
> 
> 但是因为网络问题，这个程序还要下载亚马逊和huggingface里的配置文件和模型，我尝试过手动导入，但是我代码基础差看不懂，所以还是运行不了，你们如果解决了麻烦告诉我！！提前说声感谢

解决了python -m unidic download网络错误问题，谢谢！

**Comment by zhengzhezhe** [comment]
> 呃，我已经全部解决了！

请问你是怎么解决的

**Comment by Game5048-bilibili** [comment]
> > 呃，我已经全部解决了！
> 
> 请问你是怎么解决的

cmd里用代理
https://github.com/myshell-ai/MeloTTS/issues/62#issuecomment-2067618337

**Comment by YWLrgzn** [comment]
> 1, manaul download the unidic.zip from https://cotonoha-dic.s3-ap-northeast-1.amazonaws.com/unidic-3.1.0.zip, 2, cp unidic-3.1.0.zip to /usr/local/lib/python3.9/site-packages/unidic/ and rename it to unidic.zip 3, change /usr/local/lib/python3.9/site-packages/unidic/download.py line 93 , function download_version, comment all except download_and_clean(), 4, change the download_and_clean two parameter anything you want 5, change /usr/local/lib/python3.9/site-packages/unidic/download.py line 63, comment the download_process then execut python -m unidic download again , it will be OK

it's a erro ,when runing "melo-ui"
/home/orangepi/anaconda3/envs/chat/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/orangepi/anaconda3/envs/chat/lib/python3.9/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/home/orangepi/anaconda3/envs/chat/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/orangepi/anaconda3/envs/chat/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

**Comment by VastOcean-Yang** [comment]
> Try this in windows cmd
> 
> ```
> set HTTP_PROXY=http://127.0.0.1:7890
> set HTTPS_PROXY=http://127.0.0.1:7890
> python -m unidic download
> ```
> 
> Try this in bash
> 
> ```
> export HTTP_PROXY=http://127.0.0.1:7890
> export HTTPS_PROXY=http://127.0.0.1:7890
> python -m unidic download
> ```

i set ALL_PROXY but no http_proxy

thats worked! nice
