### ISSUE TITLE
pkg_resources.UnknownExtra: typer 0.12.3 has no such extra feature 'all'

### ISSUE THREAD

**Issue by guimingyue** [myshell-ai/MeloTTS#97]
When I execute the command `melo-ui` or `melo "Text to read" output.wav`, the following stacktrace were printed.

```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2791, in requires
    deps.extend(dm[safe_extra(ext)])
KeyError: 'all'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/melo", line 33, in <module>
    sys.exit(load_entry_point('melotts', 'console_scripts', 'melo')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mingyue/github/MeloTTS/melo/main.py", line 28, in main
    from melo.api import TTS
  File "/Users/mingyue/github/MeloTTS/melo/api.py", line 5, in <module>
    import librosa
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/librosa/util/__init__.py", line 78, in <module>
    from .files import *  # pylint: disable=wildcard-import
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/librosa/util/files.py", line 10, in <module>
    from pkg_resources import resource_filename
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3292, in <module>
    def _initialize_master_working_set():
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3266, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3304, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 600, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 937, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 803, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2793, in requires
    raise UnknownExtra(
pkg_resources.UnknownExtra: typer 0.12.3 has no such extra feature 'all'
```

**Comment by guimingyue** [comment]
> When I execute the command `melo-ui` or `melo "Text to read" output.wav`, the following stacktrace were printed.
> 
> ```python
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2791, in requires
>     deps.extend(dm[safe_extra(ext)])
> KeyError: 'all'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.9/bin/melo", line 33, in <module>
>     sys.exit(load_entry_point('melotts', 'console_scripts', 'melo')())
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/Users/mingyue/github/MeloTTS/melo/main.py", line 28, in main
>     from melo.api import TTS
>   File "/Users/mingyue/github/MeloTTS/melo/api.py", line 5, in <module>
>     import librosa
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/librosa/__init__.py", line 209, in <module>
>     from . import core
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/librosa/core/__init__.py", line 5, in <module>
>     from .convert import *  # pylint: disable=wildcard-import
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/librosa/core/convert.py", line 7, in <module>
>     from . import notation
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/librosa/core/notation.py", line 8, in <module>
>     from ..util.exceptions import ParameterError
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/librosa/util/__init__.py", line 78, in <module>
>     from .files import *  # pylint: disable=wildcard-import
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/librosa/util/files.py", line 10, in <module>
>     from pkg_resources import resource_filename
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3292, in <module>
>     def _initialize_master_working_set():
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3266, in _call_aside
>     f(*args, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3304, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 600, in _build_master
>     ws.require(__requires__)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 937, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 803, in resolve
>     new_requirements = dist.requires(req.extras)[::-1]
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2793, in requires
>     raise UnknownExtra(
> pkg_resources.UnknownExtra: typer 0.12.3 has no such extra feature 'all'
> ```

Env

```shell
OS: Mac Monterey 12.7.4
Chip: Intel i7
Python: 3.9
pip: 19.2.3
```

**Comment by guimingyue** [comment]
Interesting，this error disappeared after I upgrade pip3 to 24.0

**Comment by huwprosser** [comment]
My solve for this was using python 3.10

**Comment by allonx** [comment]
I had tried many solutions.
pip install ''typer[all]<0.12"
It's the best method for python3.9.
